# Model arguments
model_name_or_path: Gensyn/Qwen2.5-0.5B-Instruct
model_revision: main
torch_dtype: float16
attn_implementation: flash_attention_2
bf16: false
tf32: false
output_dir: runs/gsm8k/multinode/Qwen2.5-0.5B-Instruct-Gensyn-Swarm

# Dataset arguments
dataset_id_or_path: 'openai/gsm8k'

# Lora Arguments
# No LoRA is used here

# Training arguments
max_steps: 2
per_device_train_batch_size: 1
gradient_accumulation_steps: 64
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 1e-7
lr_scheduler_type: cosine
warmup_ratio: 0.03
# GRPO specific parameters
beta: 0.0001
max_prompt_length: 32
max_completion_length: 128
num_generations: 1
temperature: 0.1
top_k: 10
top_p: 0.9
use_vllm: false
vllm_gpu_memory_utilization: 0.1

# Logging arguments
logging_strategy: steps
logging_steps: 1
report_to:
- tensorboard
save_strategy: "steps"
save_steps: 2
seed: 42

# Hugging Face Hub
# push_to_hub: false
# hub_strategy: every_save

# Script arguments
# 10000 is approximately infinite
max_rounds: 10000

training_args:
  gradient_accumulation_steps: 64
  per_device_train_batch_size: 1
  max_grad_norm: 0.1
  optim: adamw_torch
  learning_rate: 1e-7
  max_steps: 2
  save_steps: 2
  logging_steps: 1
  gradient_checkpointing: true
  fp16: true
  torch_dtype: float16
